config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sessions/new'
  root "mainnote#top"
  get 'mainnnote/mypage', to: 'mainnote#mypage'
  get 'mainnnote/about', to: 'mainnote#about'
  get 'mainnnote/usershow', to: 'mainnote#usershow'
  get 'mainnnote/userpg/:id', to: 'mainnote#userpg'
  
  resources :mainnote do
    resources :notecomments
    resources :likes, only: [:create, :destroy]
    resources :uses, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/mainnote.rb
class Mainnote < ApplicationRecord
  mount_uploader :image1, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader
  belongs_to :user
  has_many :notecomments, dependent: :destroy

  has_many :likes
  has_many :likes, dependent: :destroy

  has_many :uses
  has_many :uses, dependent: :destroy
  
  validate :title_valid
  def title_valid
    if title.blank?
      errors.add(:title, :blank)
    elsif title.length > 30
      errors.add(:title, 'は30文字以下で入力してください')
    end
  end
  validate :text_valid
  def text_valid
    if text.blank?
      errors.add(:text, :blank)
    elsif text.length > 500
      errors.add(:text, 'は500文字以内で入力してください')
    end  
  end

  validate :category_valid
  def category_valid
    if category.blank?
      errors.add(:category, :blank) 
    end  
  end

  validate :target_valid
  def target_valid
    if target.blank?
      errors.add(:target, :blank) 
    end  
  end
end

app/controllers/mainnote_controller.rb
class MainnoteController < ApplicationController
  before_action :authenticate_user!, except: [:top,:about]
  def top
    @q = Mainnote.ransack(params[:q])
    @mainnote = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def show
    @mainnote = Mainnote.find(params[:id])
    @user_mainnote= User.where(id: @mainnote.user_id)
    @notecomment = Notecomment.where(mainnote_id: @mainnote.id)
    @like = Like.new
    @use = Use.new
  end

  def new
    @mainnote = Mainnote.new
  end
  
  def create
    @mainnote = Mainnote.new(mainnote_params)

    if @mainnote.save
      redirect_to @mainnote
    else
      render :new
    end
  end

  def edit
    @mainnote = Mainnote.find(params[:id])
    unless @mainnote.user_id == current_user.id
      redirect_to  @mainnote
    end
  end

  def update
    @mainnote = Mainnote.find(params[:id])
    if params[:delete_image1]
         @mainnote.image1 = nil
         @mainnote.save!
         render :action => 'edit'
         return
    end
    if params[:delete_image2]
         @mainnote.image2 = nil
         @mainnote.save!
         render :action => 'edit'
         return
    end
    if params[:delete_image3]
         @mainnote.image3 = nil
         @mainnote.save!
         render :action => 'edit'
         return
    end
    if @mainnote.update(mainnote_params)
      redirect_to @mainnote
    else
      render :edit
    end  
  end


  def destroy
    @mainnote = Mainnote.find(params[:id])
    if @mainnote.user_id != current_user.id
      redirect_to  @mainnote
    else
      @mainnote.destroy
      redirect_to root_path
    end
  end

  def about

  end

  def usershow
    @user = User.all
  end

  def mypage
    @mainnote = Mainnote.where(user_id: current_user.id)
    @notecomment = Notecomment.where(mainnote_id: @mainnote.ids)
  end

  def userpg
      @user = User.find(params[:id])
      @mainnote = Mainnote.where(user_id: @user.id)
      @notecomment = Notecomment.where(mainnote_id: @mainnote.ids)
  end
  
  private
    def mainnote_params
      params.require(:mainnote).permit(:user_id, :text, :title, :image1, :image2, :image3, :category, :target, :thingstoprepare)
    end


end

app/helpers/mainnote_helper.rb
module MainnoteHelper
end

app/views/mainnote/about.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div> 

<div class="main_background"> 
  <div class="main_zone">
    <h2 class="page_title">工夫FACTORYとは？</h2>
    <div class="main_border">
      <div class="about_contents_area">
        <img src="/assets/about_factory3.jpeg" class="about_top_image">
        <p>工夫ファクトリーとは工夫を発信するSNSです。</p>
        <p>人は生活する上で知恵を絞り、様々な工夫を施します。</p>
        <p>工夫によって、生活をより良いものに変化させることができます。</p>
        <p>培った工夫は他のユーザーにも変化をもたらすかもしれません。</p>
        <p>仕事,健康,運動,節約,などあなたの工夫を投稿してみませんか？</p>
        <div class="about_images">  
          <img src="/assets/about_factory5.jpeg"class="about_image">
          <img src="/assets/about_factory7.jpeg"class="about_image">
          <img src="/assets/about_factory.jpeg"class="about_image">  
        </div>
        <p><strong>使ってもらうことで貢献ランクをあげよう！</strong></p>
        <img src="/assets/judge_factory.jpeg" class="about_bottom_image">  
        <p>当サイトではランク機能を設けています。</p>
        <p>いいね！使います！を獲得することでランクアップしていきます。</p>
        <p>沢山の工夫を発信して最高ランクを目指そう！</p>
      </div>  
    </div>  
  </div>
</div>  

app/views/mainnote/edit.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div>
<div class="main_background"> 
  <div class="main_zone">
    <h2 class="page_title">工夫内容更新</h2>
    <div class="main_border">
      <div class="form_background">
        <%= form_with model: @mainnote,:url => {:action => :update}  do |form| %>
          <div class="form_area">
            <p class="label_width"><strong><%= form.label :"タイトル" %></strong>　<span style="color:red">※必須</span></p>
            <%boolen_title=""%>
            <% @mainnote.errors.full_messages_for(:title).each do |message| %>
              <%boolen_title="false"%>
            <% end %>
            <div>
              <%if boolen_title == "false"%>
                <%= form.text_area :title, class: "error_form" %>
                <% @mainnote.errors.full_messages_for(:title).each do |message| %>
                  <p class="error_massege_text"><strong><%= message %></strong></p>
                <% end %>
              <%else%>
                  <%= form.text_area :title, class:"form_size" %>
              <%end%>
            </div>  
          </div>   
          <hr>
          <div class="form_area">       
            <p class="label_width"><strong><%= form.label :"詳細" %></strong>　<span style="color:red">※必須</span></p>
            <%boolen_text=""%>
            <% @mainnote.errors.full_messages_for(:text).each do |message| %>
              <%boolen_text="false"%>
            <% end %>
            <div>
              <%if boolen_text == "false"%>
                <%= form.text_area :text, class:"error_form" %>
                <% @mainnote.errors.full_messages_for(:text).each do |message| %>
                  <p class="error_massege_text"><strong><%= message %></strong></p>
                <% end %>
              <%else%>
                <%= form.text_area :text, class:"form_size" %>
              <%end%> 
            </div>  
          </div>  
          <hr>
          <div class="form_area">
            <p class="label_width"><strong><%= form.label :"ターゲット" %></strong>　<span style="color:red">※必須</span></p>
            <%boolen_target=""%>
            <% @mainnote.errors.full_messages_for(:target).each do |message| %>
              <%boolen_target="false"%>
            <% end %>
            <div>  
              <%if boolen_target == "false"%>
                <%= form.text_area :target, class:"error_form" %>
                <% @mainnote.errors.full_messages_for(:target).each do |message| %>
                  <p class="error_massege_text"><strong><%= message %></strong></p>
                <% end %>
              <%else%>      
                <%= form.text_area :target, class:"form_size" %>
              <% end %> 
            </div>  
          </div> 
          <hr>
          <div class="form_area">
            <p class="label_width"><strong><%= form.label :"カテゴリー" %></strong>　<span style="color:red">※必須</span></p>
            <%boolen_category=""%>
            <% @mainnote.errors.full_messages_for(:category).each do |message| %>
              <%boolen_category="false"%>
            <% end %>
            <div>
              <%if boolen_category == "false"%>
                <%= form.select :category,[["生活", "生活"], ["仕事", "仕事"], ["健康", "健康"], ["節約", "節約"], ["工夫アイテム", "工夫アイテム"], ["その他", "その他"]], {include_blank: "カテゴリーを選択して下さい"}, class:"error_form" %>
                <% @mainnote.errors.full_messages_for(:category).each do |message| %>
                  <p class="error_massege_text"><strong><%= message %></strong></p>
                <% end %>
              <%else%> 
                <%= form.select :category,[["生活", "生活"], ["仕事", "仕事"], ["健康", "健康"], ["節約", "節約"], ["工夫アイテム", "工夫アイテム"], ["その他", "その他"]], {include_blank: "カテゴリーを選択して下さい"}, class:"form_size" %>
              <% end %>
            </div>  
          </div>
          <hr>
          <div class="form_area">
            <p class="label_width"><strong><%= form.label :"用意するもの" %></strong>　<span style="color:red">※必須</span></p>
            <%boolen_thingstoprepare=""%>
            <% @mainnote.errors.full_messages_for(:thingstoprepare).each do |message| %>
              <%boolen_thingstoprepare="false"%>
            <% end %>
            <div>  
              <%if boolen_thingstoprepare == "false"%>
                <%= form.text_area :thingstoprepare, class:"error_form" %>
                  <% @mainnote.errors.full_messages_for(:thingstoprepare).each do |message| %>
                  <p class="error_massege_text"><strong><%= message %></strong></p>
                <% end %>
              <%else%>      
                <%= form.text_area :thingstoprepare, class:"form_size" %>
              <% end %> 
            </div>  
          </div>
          <hr>
          <!--画像１があれば表示して削除ボタンを表示。空ならフォームを表示-->
          <div class="form_image">  
            <p class="label_width"><strong><%= form.label :画像1 %></strong></p>
              <%if @mainnote.image1.present?%>
                <div class="edit_image_form">
                  <img src=<%= @mainnote.image1 %> class="form_image_view">
                  <%= form.submit value: "添付画像を消す",name: "delete_image1",class:"delete_image_button"%>
                </div>
              <%else%>
                <label class="image_upload">
                  画像1をアップロード
                  <%= form.file_field :image1 ,accept: "image/jpg,image/jpeg,image/png",class:"file_field"%>
                </label>
              <%end%>
          </div>
          <hr>
          <!--画像２があれば表示して削除ボタンを表示。空ならフォームを表示-->
          <div class="form_image">
            <p class="label_width"><strong><%= form.label :画像2 %></strong></p>
            <%if @mainnote.image2.present?%>
              <div class="edit_image_form">
                <img src=<%= @mainnote.image2 %> class="form_image_view">
                <%= form.submit value: "添付画像を消す",name: "delete_image2",class:"delete_image_button"%>
              </div>
            <%else%>
              <label class="image_upload">
                画像2をアップロード
                <%= form.file_field :image2 ,accept: "image/jpg,image/jpeg,image/png",class:"file_field"%>
              </label>
            <%end%>
          </div>
          <hr>
          <!--画像３があれば表示して削除ボタンを表示。空ならフォームを表示-->
          <div class="form_image">
            <p class="label_width"><strong><%= form.label :画像3 %></strong></p>
            <%if @mainnote.image3.present?%> 
              <div class="edit_image_form">           
                <img src=<%= @mainnote.image3 %> class="form_image_view">
                <%= form.submit value: "添付画像を消す",name: "delete_image3",class:"delete_image_button"%>
              </div>
            <%else%>
            <label class="image_upload">
              画像3をアップロード
              <%= form.file_field :image3 ,accept: "image/jpg,image/jpeg,image/png",class:"file_field"%>
            </label>
            <%end%>
          </div>
          <hr>
          <div class="button_margin">
            <%= form.submit value:"更新",class:"main_button" %>  
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/mainnote/mypage.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div>
<div class="main_background"> 
  <div class="main_zone">  
    <h2 class="page_title">マイページ</h2>
    <div class="main_border">
      <!--ポイントをview上で計算-->
      <%likes_point=0%>
      <%uses_point=0%>
      <% @mainnote.each do |mainnote| %>
        <%likes_point+=mainnote.likes.count%>
        <%uses_point+=mainnote.uses.count%>
      <% end %>
      <% all_point=likes_point+uses_point%>
      <div class="rank_contents">
          <p><strong>工夫職人ランク</strong></p>
          <% if all_point<2 && all_point>=0%>
            <img src="/assets/Norank.png" class="userpg_rank">
          <% elsif  all_point<4 && all_point>=2%>
            <img src="/assets/Bronze.png" class="userpg_rank">
          <% elsif  all_point<6 && all_point>=4%>
            <img src="/assets/Gold.png" class="userpg_rank">
          <% elsif  all_point<8 && all_point>=6%>
            <img src="/assets/Silver.png" class="userpg_rank">
          <% elsif all_point>=8%>
            <img src="/assets/Diamond.png" class="userpg_rank">
          <%end%>
      </div>
      <div class="userpg_pointbar">
        <p><strong>いいね数: </strong><%=likes_point%>ポイント</p>  
        <p><strong>使います数: </strong><%=uses_point%>ポイント</p>   
      </div>
      <div class="userpg_userarea">
        <div class="userpg_usercategory">
          <%if @current_user.image.blank? %>
            <img src="/assets/Noimageicon.jpeg" class="userpg_user_icon">
          <% else %>
            <img src=<%= @current_user.image %> class="userpg_user_icon"> 
          <%end%>
          <p class="userpg_user_name"><strong><%= @current_user.username %></strong></p>
        </div>
        <hr>
        <div class="userpg_user_category">
          <p class="userpg_category_label"><strong>職業:</strong></p>
          <p class="userpg_category_text"><%=current_user.occupation%></p>
        </div>
        <hr>
        <div class="userpg_user_category">
          <p class="userpg_category_label"><strong>一言:</strong></p>
          <p class="userpg_category_text"><%= current_user.award%></p>
        </div>
        <div class="userpg_edit_button">
          <%= link_to ' ユーザー情報編集', edit_user_registration_path%>
        </div>
      </div>  
      <h3 class="userpg_category">投稿した工夫一覧</h3>
      <div class="main_center">
        <% @mainnote.each do |mainnote| %>
          <div class="top_contents">
            <div class="top_user_contents">
              <% @user_mainnote=User.where(id: mainnote.user_id) %>        
              <% @user_mainnote.each do |user| %>
                <%if user.image.blank? %>
                  <img src="/assets/Noimageicon.jpeg" class="top_user_icon">
                <% else %>
                  <img src=<%= user.image %>  class="top_user_icon">
                <%end %>
                <p><%= link_to current_user.username, mainnnote_mypage_path %></p>
              <%end%>
            </div>
            <%if mainnote.image1.blank? %>
              <%=link_to image_tag("/assets/Noimage.png", class:"top_content_image"), mainnote%>
              <% else %>
              <%=link_to image_tag(mainnote.image1.url, class:"top_content_image"), mainnote%>
            <%end %>
            <p><strong><%= link_to mainnote.title, mainnote %></strong></p>
          </div> 
        <% end %>
      </div>
    </div>
  </div>
</div>    

app/views/mainnote/show.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div>
<div class="main_background"> 
  <div class="main_zone">  
    <h2 class="page_title"><%=@mainnote.title%></h2>
    <div class="main_border">
      <!--ログインしているユーザーのみに更新削除をできるように設定。コントローラーでもできるが、ボタンを表示させたくないのでviewで条件を設定。-->
      <div class="show_images">
        <%if @mainnote.image1.blank? %>
          <img src="/assets/Noimage.png" class="show_content_image">
        <% else %>
          <a href=<%= @mainnote.image1 %> target="_blank"><img src=<%= @mainnote.image1 %> class="show_content_image"></a>
        <%end %>
        <%if @mainnote.image2.blank? %>
          <img src="/assets/Noimage.png" class="show_content_image">
        <% else %>
          <a href=<%= @mainnote.image2 %> target="_blank"><img src=<%= @mainnote.image2 %> class="show_content_image"></a>
        <%end %>
        <%if @mainnote.image3.blank?%>
          <img src="/assets/Noimage.png" class="show_content_image">
        <% else %>
          <a href=<%= @mainnote.image3 %> target="_blank"><img src=<%= @mainnote.image3 %> class="show_content_image"></a>
        <%end %>  
      </div>
      <div class="show_zone">  
        <h3 class="show_label">説明</h3>
        <div class="show_content_text">
          <p><%=safe_join(@mainnote.text.split("\n"),tag(:br))%></p>
        </div>
        <div class="show_top_contents">  
          <% if @mainnote.user_id == current_user.id %>
            <%= button_to "#{@mainnote.likes.count}"+"いいね" , mainnote_likes_path(@mainnote),class:"like_before", :disabled=>true %>
            <%= button_to "#{@mainnote.uses.count}"+"使います" , mainnote_uses_path(@mainnote) ,class:"use_before", :disabled=>true %>
          <% else %>
            <% if current_user.already_liked?(@mainnote) %>
              <%= button_to "#{@mainnote.likes.count}"+"いいね" , mainnote_like_path(@mainnote), method: :delete ,class:"like_after" %>
            <% else %>
              <%= button_to "#{@mainnote.likes.count}"+"いいね" , mainnote_likes_path(@mainnote),class:"like_before" %>
            <% end %>
            <% if current_user.already_used?(@mainnote) %>
              <%= button_to "#{@mainnote.uses.count}"+"使います" , mainnote_use_path(@mainnote), method: :delete,class:"use_after" %>
            <% else %>
              <%= button_to "#{@mainnote.uses.count}"+"使います" , mainnote_uses_path(@mainnote) ,class:"use_before"%>
            <% end %>
          <% end %>
        </div>
        <div class="show_category">
          <div class="show_content_category">
            <p class="show_category_label"><strong>カテゴリー:</strong></p>
            <p class="show_category_text"><%=@mainnote.category%></p>
          </div>
          <hr>
          <div class="show_content_category">
            <p class="show_category_label"><strong>ターゲット:</strong></p>
            <p class="show_category_text"><%=@mainnote.target%></p>
          </div>
          <hr>
          <div class="show_content_category">
            <p class="show_category_label"><strong>用意するもの:</strong></p>
            <p class="show_category_text"><%=@mainnote.thingstoprepare%></p>
          </div>
        </div>
        <div class="show_user_contents">
          <% @user_mainnote.each do |user| %>
            <p>投稿者</p>
            <%if user.image.blank? %>
              <img src="/assets/Noimageicon.jpeg" class="user_icon">
            <% else %>
              <img src=<%= user.image %> class="user_icon">
            <%end%>
              <p><strong><%= user.username %></strong></p>
          <% end %>
        </div>
        <div class="show_top_contents">
          <% if @mainnote.user_id == current_user.id %>
            <p><strong><%= link_to "工夫の更新", edit_mainnote_path(@mainnote) %></strong></p>
            <p><strong><%= link_to "工夫の削除", mainnote_path(@mainnote),method: :delete,data: { confirm: "本当に削除しますか?" } %></strong></p>
          <%end%>     
        </div>
        <%= render "notecomments/comment" %>
        <%= render "notecomments/form" %>
      </div>  
    </div>
  </div>
</div>  

app/views/mainnote/top.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div>
<div class="main_background"> 
  <div class="main_zone">  
  <%= search_form_for(@q, url: root_path) do |f| %>
    <%= f.label :title_cont %>
    <%= f.search_field :title_cont %>
    <%= f.select :category_eq, options_for_select({仕事: "仕事", 生活: "生活", 健康: "健康"}),include_blank: true %>
    <%= f.submit %>
<% end %>
    <h2 class="page_title">トップ</h2>
    <div class="main_border">
      <div class="main_center">
        <% @mainnote.each do |mainnote| %>
          <div class="top_contents">
            <div class="top_user_contents">
              <% @user_mainnote=User.where(id: mainnote.user_id) %>        
              <% @user_mainnote.each do |user| %>
                  <%if user.image.blank? %>
                    <img src="/assets/Noimageicon.jpeg" class="top_user_icon">
                  <% else %>
                  <img src=<%= user.image %>  class="top_user_icon">
                  <%end %>
                <%if current_user!=nil%> 
                  <% if user.id == current_user.id%>
                      <p><%= link_to current_user.username, mainnnote_mypage_path %></p>
                  <% else %>
                      <p><%= link_to user.username, "mainnnote/userpg/#{user.id}" %></p>
                  <%end%>
                <%else%>
                  <p><%= link_to user.username, "mainnnote/userpg/#{user.id}" %></p>
                <%end%>  
              <%end%>
            </div>
            <%if mainnote.image1.blank? %>
              <%=link_to image_tag("/assets/Noimage.png", class:"top_content_image"), mainnote%>
              <% else %>
              <%=link_to image_tag(mainnote.image1.url, class:"top_content_image"), mainnote%>
            <%end %>
            <p><strong><%= link_to mainnote.title, mainnote %></strong></p>
          </div> 
        <% end %>
      </div>
      <div class="paginate">
        <%= paginate @mainnote %>
      </div>  
    </div>
  </div>
</div>

app/views/mainnote/usershow.html.erb
<div class="main_zone">
  <nav id="menuber_top">
    <ul>
      <%if current_user==nil%> 
        <li><%= link_to "新機登録", new_registration_path(resource_name) %><br /></li>
        <li><%= link_to "ログイン", new_session_path(resource_name) %><br /></li>
      <%else%>
        <li><%= link_to "マイページ", mainnnote_mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :get %></li>
      <%end%>    
    </ul>
  </nav>  
  <h1 class="main_title">工夫FACTORY</h1>
  <nav id="menuber">
    <ul class="menu_text">
      <li><%= link_to "サイトトップ　", root_path %></li>
      <li><%= link_to "サイトについて", mainnnote_about_path %></li>
      <li><%= link_to "新規工夫投稿　", new_mainnote_path %></li>   
      <li><%= link_to "工夫職人一覧　", mainnnote_usershow_path %></li>
    </ul>
  </nav>
</div>
<!--ユーザー一覧を表示。ログインしているユーザーにはマイページのリンクを表示させる。-->
<div class="main_background"> 
  <div class="main_zone">  
    <h2 class="page_title">工夫職人一覧</h2>
    <div class="main_border">
      <div class="usershowpg_area">
        <div class="main_center">
          <% @user.each do |user| %>
            <div class="usershow_user_area">
              <% if user.id == current_user.id%>
                <%if current_user.image.blank? %>
                  <%=link_to image_tag("/assets/Noimageicon.jpeg", class:"user_icon"), mainnnote_mypage_path%>
                  <p class="top_user_name"><%= link_to current_user.username, mainnnote_mypage_path %></p>
                <% else %>
                  <%=link_to image_tag(current_user.image.url, class:"user_icon"), mainnnote_mypage_path%>           
                  <p class="top_user_name"><%= link_to current_user.username, mainnnote_mypage_path %></p>
                <%end %>
              <% else %>
                <%if user.image.blank? %>
                  <%=link_to image_tag("/assets/Noimageicon.jpeg", class:"user_icon"), "userpg/#{user.id}"%>           
                  <p class="top_user_name"><%= link_to user.username, "userpg/#{user.id}" %></p>
                <% else %>
                  <%=link_to image_tag(user.image.url, class:"user_icon"), "userpg/#{user.id}"%>
                  <p class="top_user_name"><%= link_to user.username, "userpg/#{user.id}" %></p>
                <%end %>
              <% end %>
            </div>  
          <% end %>
        </div>
      </div>  
    </div>
  </div>
</div>